/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteupsRouteImport } from './routes/writeups'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MediumRouteImport } from './routes/medium'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriteupsSlugRouteImport } from './routes/writeups.$slug'

const WriteupsRoute = WriteupsRouteImport.update({
  id: '/writeups',
  path: '/writeups',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MediumRoute = MediumRouteImport.update({
  id: '/medium',
  path: '/medium',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteupsSlugRoute = WriteupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WriteupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/labs': typeof LabsRoute
  '/medium': typeof MediumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writeups': typeof WriteupsRouteWithChildren
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/labs': typeof LabsRoute
  '/medium': typeof MediumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writeups': typeof WriteupsRouteWithChildren
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/labs': typeof LabsRoute
  '/medium': typeof MediumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writeups': typeof WriteupsRouteWithChildren
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certifications'
    | '/labs'
    | '/medium'
    | '/sitemap.xml'
    | '/writeups'
    | '/writeups/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certifications'
    | '/labs'
    | '/medium'
    | '/sitemap.xml'
    | '/writeups'
    | '/writeups/$slug'
  id:
    | '__root__'
    | '/'
    | '/certifications'
    | '/labs'
    | '/medium'
    | '/sitemap.xml'
    | '/writeups'
    | '/writeups/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificationsRoute: typeof CertificationsRoute
  LabsRoute: typeof LabsRoute
  MediumRoute: typeof MediumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WriteupsRoute: typeof WriteupsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writeups': {
      id: '/writeups'
      path: '/writeups'
      fullPath: '/writeups'
      preLoaderRoute: typeof WriteupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medium': {
      id: '/medium'
      path: '/medium'
      fullPath: '/medium'
      preLoaderRoute: typeof MediumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writeups/$slug': {
      id: '/writeups/$slug'
      path: '/$slug'
      fullPath: '/writeups/$slug'
      preLoaderRoute: typeof WriteupsSlugRouteImport
      parentRoute: typeof WriteupsRoute
    }
  }
}

interface WriteupsRouteChildren {
  WriteupsSlugRoute: typeof WriteupsSlugRoute
}

const WriteupsRouteChildren: WriteupsRouteChildren = {
  WriteupsSlugRoute: WriteupsSlugRoute,
}

const WriteupsRouteWithChildren = WriteupsRoute._addFileChildren(
  WriteupsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificationsRoute: CertificationsRoute,
  LabsRoute: LabsRoute,
  MediumRoute: MediumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WriteupsRoute: WriteupsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
